# Generated by Django 4.0.3 on 2022-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(blank=True, max_length=100, null=True)),
                ('byWho', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('valuta', models.CharField(blank=True, max_length=100, null=True)),
                ('Kurs', models.IntegerField()),
                ('summa', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('izoh', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
