# Generated by Django 4.0.3 on 2022-04-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='typee',
            field=models.CharField(blank=True, choices=[('KIRIM', 'KIRIM'), ('CHIQIM', 'CHIQIM'), ('DIVIDEND', 'DIVIDEND'), ('PERSONAL', 'PERSONAL')], max_length=100, null=True),
        ),
    ]
